version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.1
    ports:
      - ${POSTGRES_PORT}:5432
    expose:
      - ${POSTGRES_PORT}
    env_file:
      - .env.database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5

  # kitajs:
  #   container_name: kitajs

  # nestjs:
  #   container_name: nestjs

networks:
  tcc_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
